apiVersion: apps/v1
kind: Deployment
metadata:
  name: hardening-demo
  namespace: hardening-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hardening-demo
  template:
    metadata:
      labels:
        app: hardening-demo
    spec:
      containers:
        - name: app
          image: dockerapp:v1
          ports:
            - containerPort: 8080
          
          # YAHAN SE UPDATE SHURU HAI
          envFrom:
            - secretRef:
                name: app-port-config # Yeh wahi secret hai jo SealedSecret ne banaya hai
          # YAHAN TAK UPDATE HAI

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            # Ek choti si suggestion: runAsUser bhi add kar sakte ho safety ke liye
            runAsUser: 1000
