apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-port-config
  namespace: hardening-demo
spec:
  encryptedData:
    PORT: AgBM9IfZvxKUSTVM3XhaYgRZaY5CwTwzkMlfSYUJc22oeqa5UJUGKLjIMKNt9hUBg6rEUfDKa60CZFD7DrqruOrdbeOrQyLKd4qUggU+2Cau9ozLMEq6JN2wO2V9s/Yz+YDHMpNmZ9gvNV/On4MDmFmG+E86TdbcYQZf/pRIb8Ljyqmy8fo7G0MgGGgXaTsQrY6ymMK9U9GLf4zsH5CPLmAPYqfJxAqU3ORqdhuOb2JZLUvd/BFqm5GVtetXQBXTqVYP7N1AjyJbx3Y1fw8C44/0hXNmj99hD6Wap/WsvperKPj4sXLptf1EC/tT3ycLMRP9kUG/L2u/4sCsGd4huqp9ni+vlFNAXXvldsbsYVpgDwfHtwcoqlcy6LX2aw2xxHxPbka7bgG7KWxz4PTfO3HMfoWSonnUnH2dTuvVaVjnlBVcM0qMXyRKDfY6z7Ki4qdV7MunV9bx5I89Trz46Vj/jb2ePRH3rdCfxsgxICJiKSkWYgudpbrSsp32fGRa6L7nhf+vMcfYm+0UCCS92U1fgaaikAdujuTUfSGwZIqPj/7cyubttPUs2Le33eztckE+Po/FmNDril1AFlC9pDSnGazkFRy9uc/2BLaNx84Fws4aUf5pndFEL30LOyC/2DiOKf8Git2AOeafLQPqCkYRnzRR2kY0i4IjSdA9MLF2vqigZpZ/owFy8yAE2BSoKep567Ne
  template:
    metadata:
      name: app-port-config
      namespace: hardening-demo
