apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: hardening-demo
spec:
  encryptedData:
    password: AgBdummyEncryptedValueForDemoOnly
  template:
    metadata:
      name: app-secret
      namespace: hardening-demo
    type: Opaque
