apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-port-config
  namespace: hardening-demo
spec:
  encryptedData:
    PORT: AgCXRPkxrlNQ875whf45RvfmrsqFYUIEKMiMSQToKlnxN1BfyIiiqvVi0wNWZZO7zO4FN7rgHBQ7rA/E7Qje+K6J1LXMn+otJGrvDflNhpAVeIFDUx9qhjrDZ6KwCEccn/6tVvuY6ZgrqwtFov2YelNSOT5mV54AIVJQ2+XiL0AWN6TbQgual7hLeHuU8LgERTEwkELIJ6+Bz2+YcBviWEmLEgo753AxLSvArdZZVRBBc6O4fjhJP1Eozq+hrrNDUwYhwJuzpiWWsVlraBBpaUogZOlO2VvWHcj6xuk0Hdre6mD/V2nY8CytBJLbwzJ1hJcqprpprjCnlsVJ5Hf8E0WnChYa38ZlQMQOhf5DH1IX0furvzFPlDq3FuZH7GzfrbQl8JH0+4oIEo+g6KIhQwaO/K3dkh5vr7tIi/tQ4AZXQoee/FbqACeKIUKKPUFER0IfugLAom7kV0PjBYdp3T5i1Zu2YCTSqZ84rXbv/2fXs7jO/HezJMTUI/NfoX3NsTGf+76C1Om7mbxn/UnzGsvgKSq/hRki/YHynHj2c25/jln6nqccZgrAyMn8KAw1YTUL3LcloviheNoMJzmz0oFww3P0z6WrvfIZkEmwIbIVikfM9UerITx8hg/GPEDhIYIlxEw09WCXbBRP2FhvplsVfdpaesQ9jOVpHe8PBAqkIHRj7PTZF/OfKe5t+jPeTpdYRKgx
  template:
    metadata:
      name: app-port-config
      namespace: default
